#!/usr/bin/env python3

import requests
import click

SAMPLE_API_KEY = 'b1b15e88fa797225412429c1c50c122a1'

def current_weather(location, api_key=SAMPLE_API_KEY):
    url = 'https://api.openweathermap.org/data/2.5/weather'

    query_params = {
        'q': location,
        'appid': api_key,
    }

    response = requests.get(url, params=query_params)
    
    return response.json()['weather'][0]['description']

@click.command()
@click.argument('location')
@click.option(
    '--api-key', '-a',
    help='your API key for the OpenWeatherMap API',
)
def main(location, api_key):
    """
    A weather tool example using the python click library

    You will need to provide location and your api key from OpenWeatherMap 
    
    Location can be a city name or city,country
    """
    weather = current_weather(location, api_key)
    print(f"The weather in {location} right now: {weather}.")

if __name__ == "__main__":
    main()
